# Проект №2

Проект выполнен в рамках курса  **"Cтатистика и анализ данных в R"** Института биоинформатики.

## Описание проекта

В проекте анализируются данные о ценности жилья в Бостоне в 1970-1980-х годах (датасет Boston).

В ходе проекта планировалось:

* Построить полную линейную модель, предсказывающую цену жилья
* Произвести её диагностику
* Сделать выводы о качестве модели
* Дать рекомендации условному "заказчику" по поводу района для постройки дома 

Детальный ход работы, отражён в файле **Report.rmd**.

# Описание данных

Я буду использовать данные о ценности жилья в бостоне в 1970-1980-х
годах. В данных представлены следующие переменные:

<pre>
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's
</pre>

Переменные chas и rad являются факторными.

``` r
data("Boston")
Boston$chas <- factor(Boston$chas)
Boston$rad <- factor(Boston$rad)
str(Boston)
```

    ## 'data.frame':    506 obs. of  14 variables:
    ##  $ crim   : num  0.00632 0.02731 0.02729 0.03237 0.06905 ...
    ##  $ zn     : num  18 0 0 0 0 0 12.5 12.5 12.5 12.5 ...
    ##  $ indus  : num  2.31 7.07 7.07 2.18 2.18 2.18 7.87 7.87 7.87 7.87 ...
    ##  $ chas   : Factor w/ 2 levels "0","1": 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ nox    : num  0.538 0.469 0.469 0.458 0.458 0.458 0.524 0.524 0.524 0.524 ...
    ##  $ rm     : num  6.58 6.42 7.18 7 7.15 ...
    ##  $ age    : num  65.2 78.9 61.1 45.8 54.2 58.7 66.6 96.1 100 85.9 ...
    ##  $ dis    : num  4.09 4.97 4.97 6.06 6.06 ...
    ##  $ rad    : Factor w/ 9 levels "1","2","3","4",..: 1 2 2 3 3 3 5 5 5 5 ...
    ##  $ tax    : num  296 242 242 222 222 222 311 311 311 311 ...
    ##  $ ptratio: num  15.3 17.8 17.8 18.7 18.7 18.7 15.2 15.2 15.2 15.2 ...
    ##  $ black  : num  397 397 393 395 397 ...
    ##  $ lstat  : num  4.98 9.14 4.03 2.94 5.33 ...
    ##  $ medv   : num  24 21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 ...

Поскольку переменные представлены в различных величинах, для построения
модели необходимо стандартизовать предикторы. Это позволит наиболее
объективно сравнивать вклад различных предикторов в объяснение
изменчивости.

``` r
Boston[, -c(4,9,14)] <- as.data.frame(apply(Boston[,-c(4,9,14)], 2, scale))
```

# Исследование полной линейной модели

## Построение модели

Построим полную линейную модель без взаимодействия предикторов.

``` r
model <- lm(medv ~ crim + zn + indus + chas + nox + rm + age + dis + rad + tax + ptratio + black + lstat, data=Boston)
summary(model)
```

    ## 
    ## Call:
    ## lm(formula = medv ~ crim + zn + indus + chas + nox + rm + age + 
    ##     dis + rad + tax + ptratio + black + lstat, data = Boston)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -15.1020  -2.7355  -0.4565   1.6821  25.9450 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 18.31176    1.15474  15.858  < 2e-16 ***
    ## crim        -0.93603    0.28114  -3.329 0.000937 ***
    ## zn           1.28032    0.32999   3.880 0.000119 ***
    ## indus        0.16300    0.43665   0.373 0.709081    
    ## chas1        2.52416    0.86318   2.924 0.003614 ** 
    ## nox         -2.03633    0.45150  -4.510 8.13e-06 ***
    ## rm           2.57544    0.29594   8.703  < 2e-16 ***
    ## age          0.01298    0.37232   0.035 0.972210    
    ## dis         -3.27342    0.42516  -7.699 7.75e-14 ***
    ## rad2         1.48891    1.47751   1.008 0.314095    
    ## rad3         4.68125    1.33530   3.506 0.000498 ***
    ## rad4         2.57623    1.18737   2.170 0.030514 *  
    ## rad5         2.91849    1.20761   2.417 0.016028 *  
    ## rad6         1.18584    1.46401   0.810 0.418342    
    ## rad7         4.87899    1.57120   3.105 0.002012 ** 
    ## rad8         4.83984    1.49166   3.245 0.001257 ** 
    ## rad24        7.46167    1.78868   4.172 3.58e-05 ***
    ## tax         -1.47439    0.65641  -2.246 0.025144 *  
    ## ptratio     -2.10523    0.31279  -6.731 4.78e-11 ***
    ## black        0.85761    0.24291   3.531 0.000454 ***
    ## lstat       -3.77923    0.36162 -10.451  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 4.694 on 485 degrees of freedom
    ## Multiple R-squared:  0.7499, Adjusted R-squared:  0.7396 
    ## F-statistic:  72.7 on 20 and 485 DF,  p-value: < 2.2e-16

## Диагностика модели

### Проверка на наличие влиятельных наблюдений

![Рисунок 1. График расстояний Кука для полной
модели](images/figure-gfm/unnamed-chunk-5-1.png)

Из графика видно, что влиятельных наблюдений нет.

### Проверка на гомогенность дисперсии и линейность взаимосвязи

![Рисунок 2. График распределения остатков полной
модели](images/figure-gfm/unnamed-chunk-6-1.png)

Дисперсия остатков распределена не равномерно. Наблюдаются сильные
отклонения при низких и высоких значениях зависимой переменной.
Некоторые наблюдения отклоняются более чем на 2 стандартных отклонения,
но в целом взаимосвязь кажется линейной.

### Проверка на нормальность распределения и коллинеарность предикторов

![Рисунок 3. Квантиль-квантильный график для остатков полной
модели](images/figure-gfm/unnamed-chunk-7-1.png)

Распределение отличается от нормального. Наюлюдаются сильные отклонения
от нормальности при высоких значениях зависимой переменной.

## Предсказания модели

Построим предсказания модели для переменной **lstat**, коэффициент
которой в полной модели равен **-3.77**.

![Рисунок 4. Зависимость переменной medv от переменной lstat c
предсказанными моделью
значениями](images/figure-gfm/unnamed-chunk-8-1.png)

Из графика видно, что переменная **lstat** хорошо описывает всю модель
только на небольшом интервале значений.

# Поиск оптимальной модели

## Удаление коллинеарных предикторов

Рассмотрим модель на предмет наличия коллинеарных предикторов, расчитав
фактор вздутия дисперсии.

``` r
VIF(model)
```

    ##              GVIF Df GVIF^(1/(2*Df))
    ## crim     1.811867  1        1.346056
    ## zn       2.496184  1        1.579932
    ## indus    4.370471  1        2.090567
    ## chas     1.101843  1        1.049687
    ## nox      4.672906  1        2.161691
    ## rm       2.007593  1        1.416896
    ## age      3.177556  1        1.782570
    ## dis      4.143583  1        2.035579
    ## rad     18.783126  8        1.201187
    ## tax      9.876853  1        3.142746
    ## ptratio  2.242683  1        1.497559
    ## black    1.352516  1        1.162977
    ## lstat    2.997620  1        1.731364

Уберём предикторы с самым большим VIF, пока не останутся только
предикторы с VIF &lt; 2.

``` r
model_1 <- update(model, .~. - rad)
VIF(model_1)
```

    ##     crim       zn    indus     chas      nox       rm      age      dis 
    ## 1.664471 2.273018 3.682265 1.061561 4.304929 1.885425 3.083009 3.954951 
    ##      tax  ptratio    black    lstat 
    ## 3.415289 1.734873 1.341459 2.937752

``` r
model_2 <- update(model_1, .~. - dis)
VIF(model_2)
```

    ##     crim       zn    indus     chas      nox       rm      age      tax 
    ## 1.638205 1.897074 3.511704 1.061233 3.949993 1.849614 2.821975 3.414851 
    ##  ptratio    black    lstat 
    ## 1.720096 1.340875 2.933530

``` r
model_3 <- update(model_2, .~. - nox)
VIF(model_3)
```

    ##     crim       zn    indus     chas       rm      age      tax  ptratio 
    ## 1.637882 1.826807 3.155735 1.057774 1.847368 2.430656 3.073277 1.504126 
    ##    black    lstat 
    ## 1.331457 2.920516

``` r
model_4 <- update(model_3, .~. - indus)
VIF(model_4)
```

    ##     crim       zn     chas       rm      age      tax  ptratio    black 
    ## 1.622496 1.695271 1.045869 1.813320 2.291640 2.209662 1.499542 1.329512 
    ##    lstat 
    ## 2.897706

``` r
# model_5 <- update(model_4, .~. - lstat)
# VIF(model_5)

model_6 <- update(model_4, .~. - tax)
VIF(model_6)
```

    ##     crim       zn     chas       rm      age  ptratio    black    lstat 
    ## 1.407383 1.684097 1.045648 1.813299 2.157710 1.351937 1.260738 2.863701

Несмотря на то, что предиктор **lstat** имеет VIF больший 2, он был
оставлен в модели, так как очень хорошо объясняет изменчивость зависимой
переменной.

## Удаление незначимых предикторов

На данный момент в нашей модели осталось 8 предикторов, однако не все
предикторы могут одинаково хорошо объяснять изменчивость модели. Для
нахождения незначимых предикторов воспользуемся подходом *backward
selection*.

    ## Single term deletions
    ## 
    ## Model:
    ## medv ~ crim + zn + chas + rm + age + ptratio + black + lstat
    ##         Df Sum of Sq   RSS    AIC  F value    Pr(>F)    
    ## <none>               12904 1656.8                       
    ## crim     1     43.63 12947 1656.5   1.6804 0.1954694    
    ## zn       1      1.28 12905 1654.8   0.0494 0.8242611    
    ## chas     1    305.02 13208 1666.6  11.7484 0.0006595 ***
    ## rm       1   2867.80 15771 1756.3 110.4581 < 2.2e-16 ***
    ## age      1     41.84 12945 1656.4   1.6116 0.2048597    
    ## ptratio  1   1246.94 14150 1701.5  48.0282 1.309e-11 ***
    ## black    1    293.32 13197 1666.2  11.2978 0.0008358 ***
    ## lstat    1   2605.67 15509 1747.9 100.3617 < 2.2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Видно, что предикторы **zn, crim, age** не влияют значимо на количество
объяснённой моделью изменчивости, поэтому их следует удалить.

После удаления незначимого предиктора модель имеет следующий вид:
<a id="optimized_model"></a>

    ## 
    ## Call:
    ## lm(formula = medv ~ chas + rm + ptratio + black + lstat, data = Boston)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -17.6281  -2.9377  -0.8882   1.5061  30.2533 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)  22.3032     0.2350  94.914  < 2e-16 ***
    ## chas1         3.3200     0.9015   3.683 0.000256 ***
    ## rm            3.2688     0.2951  11.076  < 2e-16 ***
    ## ptratio      -1.8581     0.2500  -7.432 4.67e-13 ***
    ## black         0.9232     0.2466   3.743 0.000203 ***
    ## lstat        -3.6995     0.3137 -11.792  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 5.096 on 500 degrees of freedom
    ## Multiple R-squared:  0.696,  Adjusted R-squared:  0.693 
    ## F-statistic: 228.9 on 5 and 500 DF,  p-value: < 2.2e-16

``` r
VIF(model_7)
```

    ##     chas       rm  ptratio    black    lstat 
    ## 1.019506 1.693576 1.215367 1.182497 1.913747

Видно, что VIF предиктора **lstat** стал меньше 2.

## Диагностика модели

Проведём диагностику оптимизированной модели.

![Рисунок 5. График расстояний Кука для оптимизированной
модели](images/figure-gfm/unnamed-chunk-14-1.png)

Влиятельные наблюдения отсутствуют.

![Рисунок 6. Распределение остатков для оптимизированной
модели](images/figure-gfm/unnamed-chunk-15-1.png)

Паттерны в распределении остатков не исчезли, однако теперь стало меньше
отклоняющихся более чем на 2 стандартных отклонения.

![Рисунок 7. Квантиль-квантильный график для остатков оптимизированной
модели](images/figure-gfm/unnamed-chunk-16-1.png)

    ## [1] 369 372

Распределение остатков не является нормальным.

## Задача максимизации цены дома

Ещё раз посмотрим на [модель](#optimized_model). Модель однозначно
нельзя назвать полностью оптимизированной, однако нам удалось её немного
улучшить. R^2 модели приблизительно равен **0.7**.

Для того, чтобы максимизировать цену за продаваемый дом, необходимо
учесть на какие из значимых предикторов в реальности можно повлиять,
чтобы увеличить значение зависимой переменной.

Рассмотрим предикторы по очереди:

### chas

Факторная переменная *chas* означает расположение дома у реки. Её
коэффициент в модели равен **3.32** и является наибольшим. Таким образом
цену дома можно сильно увеличить, построив его у реки.

### rm

Количественная переменная *rm* показывает среднее количество комнат в
доме. Её коэффициент в модели равен **3.27**, а значит также существенно
оказывает влияние на зависимую переменную. Увеличение количества комнат
в доме будет приводить к увеличению его стоимости.

При постройке дома заказчик непосредственно может повлиять только на эти
переменные. Однако мы также можем дать некоторые рекомендации по выбору
оптимального районе.

### ptratio

Количественная переменная *ptratio* показывает отношении количества
учеников к количеству учителей. Её коэффициент в модели равен **-1.86**.
Это значит, что более предпочтительным будет район, где на одного
учителя будет приходится меньше учеников, что, возможно, повышает
качество образования.

### black

Количественная переменная *black* показывает преобразованные данные о
проценте чернокожего населения (black = 1000(Bk - 0.63)^2, где Bk - доля
чернокожего населения). Эта переменная будет оказывать одинаковое
влияние на зависимую переменную при увеличении или уменьшении процента
чернокожего населения, однако при уменьшении могут быть достигнуты
бОльшие значения переменной *black*. Например,
1000(1 − 0.63)<sup>2</sup> &lt; 1000(0 − 0.63)<sup>2</sup>. Таким
образом можно было бы порекомендовать заказчику выбрать район с
максимальным процентом белого населения, но мы не расисты и не будем так
делать! Тем более, что значение коэффициента предиктора равно всего лишь
**0.92** и не будет оказывать столь значительное влияние на цену.

### lstat

Количественная переменная *lstat* является довольно сложной
социально-экономической характеристикой, учитывающей количество взрослых
без высшего образования и чернорабочих. Поскольку коэффициент в модели
равен **-3.7**, данный предиктор будет оказывать наиболее сильное
влияние на значение зависимой переменной. Выбор района с высокими
показателями образованности и занятости населения позволит существенно
повысить цену дома.

## Итоговая рекомендация

Наиболее выгодной будет постройка дома с более, чем 8 комнатами возле
реки в районе с большим количеством учителей, высокой образованностью
населения и высокой квалификацией рабочих.